#!/usr/bin/env node

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const outputPath = path.join(__dirname, '../src/environments/version.ts');
const packageJson = JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8'));

let gitHash = 'unknown';
try {
  gitHash = execSync('git rev-parse --short HEAD').toString().trim();
} catch (e) {
  console.warn('Could not get git hash:', e.message);
}

const content = `// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const VERSION_INFO = {
  version: '${packageJson.version}',
  gitHash: '${gitHash}',
  buildTime: '${new Date().toISOString()}'
};
`;

fs.writeFileSync(outputPath, content);
console.log(`Generated ${outputPath} with version: ${packageJson.version}, git hash: ${gitHash}`);
